# Dependabot configuration for automatic dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Singapore"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 5
    # Add reviewers to pull requests
    reviewers:
      - "NUS-ISS-Agile-Team"
    # Add labels to pull requests
    labels:
      - "dependencies"
      - "automated"
    # Group dependency updates
    groups:
      # Group all patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group Vue ecosystem updates
      vue-ecosystem:
        patterns:
          - "vue*"
          - "@vue/*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
      # Group ESLint related updates
      eslint-ecosystem:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "*eslint*"
        update-types:
          - "minor"
          - "patch"
    # Customize commit message prefix
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Ignore specific dependencies if needed
    # ignore:
    #   - dependency-name: "dependency-to-ignore"
    #     versions: ["x.x.x"]
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
