name: Build

on:
    push:
        branches: ['*']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                cache: 'npm'
                node-version: '24'
                cache-dependency-path: package-lock.json
            - name: Install dependencies
              run: npm ci
            - name: Build the project
              run: npm run build
            - name: ESLint
              run: npm run lint