name: Deploy Vue to EC2 (manual)

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'version'
            required: false
            default: 'latest'
            type: string
        command:
            description: 'deploy'
            required: true
            default: 'deploy'
            type: choice
            options:
                - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install & Build
        run: |
          npm ci
          npm run build
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Push dist to server
        run: |
          rsync -avz --delete --exclude=.git \
            dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/
      - name: Reload Nginx
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker exec nginx nginx -s reload"